//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5446
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 
namespace Documentation_v1_0 {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/Operation_v1_0.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/Operation_v1_0.xsd", IsNullable=false)]
    public partial class DocumentationAbstraction {
        
        private DocumentationAbstractionDocumentations documentationsField;
        
        /// <remarks/>
        public DocumentationAbstractionDocumentations Documentations {
            get {
                return this.documentationsField;
            }
            set {
                this.documentationsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/Operation_v1_0.xsd")]
    public partial class DocumentationAbstractionDocumentations {
        
        private DocumentationAbstractionDocumentationsDocuments documentsField;
        
        private DocumentationAbstractionDocumentationsPresentations presentationsField;
        
        /// <remarks/>
        public DocumentationAbstractionDocumentationsDocuments Documents {
            get {
                return this.documentsField;
            }
            set {
                this.documentsField = value;
            }
        }
        
        /// <remarks/>
        public DocumentationAbstractionDocumentationsPresentations Presentations {
            get {
                return this.presentationsField;
            }
            set {
                this.presentationsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/Operation_v1_0.xsd")]
    public partial class DocumentationAbstractionDocumentationsDocuments {
        
        private DocumentationAbstractionDocumentationsDocumentsDocument documentField;
        
        /// <remarks/>
        public DocumentationAbstractionDocumentationsDocumentsDocument Document {
            get {
                return this.documentField;
            }
            set {
                this.documentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/Operation_v1_0.xsd")]
    public partial class DocumentationAbstractionDocumentationsDocumentsDocument {
        
        private DocumentationAbstractionDocumentationsDocumentsDocumentStyles stylesField;
        
        private HeaderType[] contentField;
        
        private string nameField;
        
        private string titleField;
        
        /// <remarks/>
        public DocumentationAbstractionDocumentationsDocumentsDocumentStyles Styles {
            get {
                return this.stylesField;
            }
            set {
                this.stylesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Header", IsNullable=false)]
        public HeaderType[] Content {
            get {
                return this.contentField;
            }
            set {
                this.contentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/Operation_v1_0.xsd")]
    public partial class DocumentationAbstractionDocumentationsDocumentsDocumentStyles {
        
        private DocumentationAbstractionDocumentationsDocumentsDocumentStylesStyle styleField;
        
        /// <remarks/>
        public DocumentationAbstractionDocumentationsDocumentsDocumentStylesStyle Style {
            get {
                return this.styleField;
            }
            set {
                this.styleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/Operation_v1_0.xsd")]
    public partial class DocumentationAbstractionDocumentationsDocumentsDocumentStylesStyle {
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/Operation_v1_0.xsd")]
    public partial class HeaderType {
        
        private ParagraphTypeText[][] paragraphField;
        
        private HeaderType[] headerField;
        
        private string textField;
        
        private int levelField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Text", typeof(ParagraphTypeText), IsNullable=false)]
        public ParagraphTypeText[][] Paragraph {
            get {
                return this.paragraphField;
            }
            set {
                this.paragraphField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Header")]
        public HeaderType[] Header {
            get {
                return this.headerField;
            }
            set {
                this.headerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int level {
            get {
                return this.levelField;
            }
            set {
                this.levelField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/Operation_v1_0.xsd")]
    public partial class ParagraphTypeText {
        
        private string textContentField;
        
        private string styleRefField;
        
        /// <remarks/>
        public string TextContent {
            get {
                return this.textContentField;
            }
            set {
                this.textContentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string styleRef {
            get {
                return this.styleRefField;
            }
            set {
                this.styleRefField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/Operation_v1_0.xsd")]
    public partial class DocumentationAbstractionDocumentationsPresentations {
        
        private DocumentationAbstractionDocumentationsPresentationsPresentation presentationField;
        
        /// <remarks/>
        public DocumentationAbstractionDocumentationsPresentationsPresentation Presentation {
            get {
                return this.presentationField;
            }
            set {
                this.presentationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/Operation_v1_0.xsd")]
    public partial class DocumentationAbstractionDocumentationsPresentationsPresentation {
        
        private DocumentationAbstractionDocumentationsPresentationsPresentationSlides slidesField;
        
        private string nameField;
        
        private string titleField;
        
        /// <remarks/>
        public DocumentationAbstractionDocumentationsPresentationsPresentationSlides Slides {
            get {
                return this.slidesField;
            }
            set {
                this.slidesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/Operation_v1_0.xsd")]
    public partial class DocumentationAbstractionDocumentationsPresentationsPresentationSlides {
        
        private object slideField;
        
        /// <remarks/>
        public object Slide {
            get {
                return this.slideField;
            }
            set {
                this.slideField = value;
            }
        }
    }
}
